fix: update gitlab CI script to integrate harbor

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,73 @@
+.helm-script: &helm-script |
+  echo -n sha256: > digest_file
+  dir=helm; find "$dir" -type f -exec sha256sum {} \; | sed "s~$dir~~g" | sort -d | sha256sum | cut -d ' ' -f 1 >> digest_file
+  echo Initial Digest:
+  cat digest_file
+
+  # call reliza and see if this file system artifact was already registered before
+  docker run --rm relizaio/reliza-cli checkhash \
+  -u RELIZA_HUB_URI \
+  -i $RELIZA_PROJECT_API_ID \
+  -k $RELIZA_PROJECT_API_KEY \
+  --hash $(cat digest_file) > reliza_helm_check 2>&1
+
+  echo "Response from Reliza:"
+  reliza_helm_check=$(cat reliza_helm_check)
+  echo $reliza_helm_check
+  # little sleep is needed to make sure we calculate if condition correctly
+  sleep 5
+
+  # now only create new release if no release was found with same hash
+  if [ "$reliza_helm_check" == "{}" ]
+  then
+    
+    # obtain version
+    RLZ_VER_JSON=$(docker run --rm relizaio/reliza-cli getversion -u $RELIZA_HUB_URI -i $HELM_PROJECT_API_ID -k $HELM_PROJECT_API_KEY -b $CI_COMMIT_REF_NAME --metadata GitLab)
+    echo "reliza version json found: $RLZ_VER_JSON"
+    RLZ_FULL_VER=$(echo $RLZ_VER_JSON | docker run -i --rm relizaio/jq -r ".version")
+    echo "RLZ_FULL_VER = $RLZ_FULL_VER"
+
+    # now inject new version into the chart and commit and push
+    sed -i "/version: /s/.*/version: $RLZ_FULL_VER/" $CI_PROJECT_DIR/helm/Chart.yaml
+
+    echo "committing"
+    git config --global user.name "$AUTO_COMMITTER_NAME"
+    git config --global user.email "$AUTO_COMMITTER_EMAIL"
+    git add .
+    git commit -m "fix: auto version increment for Mafia helm chart based on Reliza Hub details"
+    git push -o ci.skip "https://${GITLAB_USER_NAME}:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}"
+
+    # Push The Chart now
+    docker pull trailb/helm:latest
+    docker run --rm -v $CI_PROJECT_DIR/helm:/apps/mafia trailb/helm push mafia $CHART_REPO_URL -u $CHART_REPO_USERNAME -p $CHART_REPO_PASSWORD
+    
+    # since we just incremented version we need to recompute digest
+
+    echo -n sha256: > digest_file
+    dir=helm; find "$dir" -type f -exec sha256sum {} \; | sed "s~$dir~~g" | sort -d | sha256sum | cut -d ' ' -f 1 >> digest_file
+    echo New Digest: 
+    cat digest_file
+
+    # Construct Reliza command to stream version to reliza
+    echo -n "--artid mafia-helm-chart-$RLZ_FULL_VER " >> reliza_command
+    echo -n "--artbuildid gitlabCI_$CI_JOB_ID " >> reliza_command
+    echo -n "--artcimeta GitLab CI build " >> reliza_command
+    echo -n "--arttype file " >> reliza_command
+    echo -n "--artdigests $(cat digest_file) " >> reliza_command
+    echo -n "--datestart $BUILD_START " >> reliza_command
+    echo -n "--dateend $(date -Iseconds) " >> reliza_command
+    echo -n "-b $CI_COMMIT_REF_NAME --vcstype git --commit $commit_sha -u $RELIZA_HUB_URI -i $RELIZA_PROJECT_API_ID -k $RELIZA_PROJECT_API_KEY --vcsuri $CI_PROJECT_URL --date $(git log -1 --date=iso-strict --pretty='%ad') -v $RLZ_FULL_VER" >> reliza_command
+    cat reliza_command
+    # send version to reliza
+    echo "sending version to reliza"
+    docker run --rm relizaio/reliza-cli addrelease $(cat reliza_command)
+    exit_status=$(echo $?)
+    if [ $exit_status -ne 0 ];then echo "error on submitting metadata to Reliza Hub, failing build"; fi
+    if [ $exit_status -ne 0 ];then exit 1; fi
+  else
+    echo "Artifact is already part of another release, not duplicating reliza hub chart release"
+  fi
+
 .template-script: &template-script |
   # format of $BUILD_ENV_PARAMS: --env PRODUCTION|helm_gitlab_prod|values_gitlab_prod.yaml, --env TEST|helm_gitlab_test|values_gitlab_test.yaml, --env STAGING|helm_gitlab_staging|values_gitlab_staging.yaml
   /bin/bash -c \
